### ISSUE TITLE
How can I test this?

### ISSUE THREAD

**Issue by saileshkush95** [khadegd/august#1]
Thanks for your works. But how can I test this. In default mezzanine some features are missing like views count, sub categories, display categories name in the post etc so please also thinks about it. I know this can be achieved manually.

**Comment by khadegd** [comment]
Did you mean, how can I try it? If you want to try it out. Run these.
```
pipenv install -e "git+https://github.com/khadegd/august.git#egg=Mezzanine"
pipenv shell
mezzanine-project helloworld
cd helloworld
python manage.py createdb
python manage.py runserver
```
